Numpy-Numerical python

In [1]:
list1=[1,5,6,7,8]
for i in list1:
    x=i+2
    print(x)

3
7
8
9
10


In [2]:
list2=[6,7,8,9,8]
list1+list2

[1, 5, 6, 7, 8, 6, 7, 8, 9, 8]

In [3]:
list1=[1,5,6,7,8]

list1*3

[1, 5, 6, 7, 8, 1, 5, 6, 7, 8, 1, 5, 6, 7, 8]

In [4]:
type(list1)

list

In [5]:
import numpy as np
n=np.array(list1)

In [6]:
type(n)

numpy.ndarray

In [8]:
print(n+2)

[ 3  7  8  9 10]


In [9]:
print(n*3)

[ 3 15 18 21 24]


In [10]:
n1=np.array(list2)

In [12]:
n+n1

array([ 7, 12, 14, 16, 16])

In [14]:
list3=(2,5,6)
n3=np.array(list3)

In [15]:
type(n3)

numpy.ndarray

In [17]:
#Create a numpy array
ar=np.array([6,8,9,4,2])
type(ar)

numpy.ndarray

In [18]:
ar.ndim # which dimension

1

In [19]:
ar.shape # no.of rows and column

(5,)

In [20]:
ar.size# number of elements

5

In [21]:
ar.dtype

dtype('int64')

In [22]:
# numpy array is homogenous datatype
ar

array([6, 8, 9, 4, 2])

In [27]:
ar1=np.array([6,7,7.5,8,9,"hi",True])
ar1

array(['6', '7', '7.5', '8', '9', 'hi', 'True'], dtype='<U32')

In [25]:
ar1.dtype

dtype('float64')

In [34]:
#ar2=np.arange(0,9)
ar2=np.arange(0,9,2)
ar2

array([0, 2, 4, 6, 8])

In [35]:
ar3=np.linspace(1,10,20)
ar3

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [48]:
np.random.seed(1)
np.random.random(8)# random it will float value only

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01])

In [51]:
#genearte random integer value
np.random.randint(10)

2

In [53]:
np.random.randint(1,2,5)

array([1, 1, 1, 1, 1])

In [54]:
#create 2D array

ar2=np.array([[1,2,5,4],[8,9,5,4]])
ar2



array([[1, 2, 5, 4],
       [8, 9, 5, 4]])

In [55]:
ar2.ndim

2

In [56]:
ar2.shape   # 1st value represent row and value represent column

(2, 4)

In [57]:
ar2.size # total elements

8

In [58]:
ar2.dtype

dtype('int64')

In [59]:
ar2.astype(float)# data type conversion

array([[1., 2., 5., 4.],
       [8., 9., 5., 4.]])

In [61]:
np.random.rand(3,5)

array([[0.27304997, 0.0592432 , 0.67052804, 0.59306552, 0.6716541 ],
       [0.41178788, 0.1975509 , 0.28962964, 0.14212014, 0.78331447],
       [0.41253884, 0.03417131, 0.62402999, 0.66063573, 0.29849529]])

In [67]:
np.random.seed(0)
np.random.randint(1,10,(3,4))   #(1,10) is range of value   (3,4) shape

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])

In [68]:
#Slicing/indexing

np.random.seed(5)
ar1=np.random.randint(1,10,8)
ar2=np.random.randint(1,10,(4,3))

In [69]:
ar1


array([4, 7, 7, 1, 9, 5, 8, 1])

In [70]:
ar1[0]

4

In [71]:
ar1[-1]

1

In [72]:
ar1[2:5]

array([7, 1, 9])

In [73]:
ar1[4:]

array([9, 5, 8, 1])

In [74]:
ar2

array([[1, 8, 2],
       [6, 8, 1],
       [2, 5, 7],
       [3, 2, 3]])

In [75]:
ar2[0,0]

1

In [76]:
ar2[2,2]

7

In [77]:
ar2[:,0]

array([1, 6, 2, 3])

In [78]:
# access the first 2 column
ar2[:,[0,1]]

array([[1, 8],
       [6, 8],
       [2, 5],
       [3, 2]])

In [79]:
# access the first 2 rows
ar2[[0,1],:]

array([[1, 8, 2],
       [6, 8, 1]])

In [81]:
ar2[:2,:2]

array([[1, 8],
       [6, 8]])

In [82]:
ar2[[0,2],:]

array([[1, 8, 2],
       [2, 5, 7]])